### ISSUE TITLE
Remove Sheet-level template

### ISSUE THREAD

**Issue by jfcorbett** [startables/startable-standard#13]
Sheet-level (or file-level?) template line (marked by `:::`) is poorly defined (see table [here](https://github.com/startable/startable-standard/blob/master/StarTable%20format%20specification.md#template-block): ambiguity between "sheet" and "file") and not modelled at all in current readers and data structures (`pdtable`, `startables` etc.). 

Let's remove it from the standard until such time as it can find a proper use case and be defined unambiguously. 

FYI @JanusWesenberg @vegatheil

**Comment by JanusWesenberg** [comment]
I believe my original motivation for including the file-level template information was that for the multi-file setups I am interested in, templates would need to be defined for separate files and I was considering a single data structure to hold template-information across files.

Handling this file-template mapping on another layers is a much nicer approach, so I think this proposal is sound.
